export type Results<T> = {
	head: { title: string, status: number },
	body: T[]
};

export type Outline = {
	element: string, // "outline",
	type: string, // "audio",
	text: string, // "KUER-FM",
	URL: string, // "http://opml.radiotime.com/Tune.ashx?id=s35868",
	bitrate: string, // "128",
	reliability: string, // "99",
	guide_id: string, // "s35868",
	subtext: string, // "All Things Considered & KUER Local News",
	genre_id: string, // "g266",
	formats: string, // "mp3",
	show_id: string, // "p1272698",
	item: string, // "station",
	image: string, // "http://cdn-radiotime-logos.tunein.com/s35868q.png"
	current_track: string, // "All Things Considered & KUER Local News"
	now_playing_id: string, // "s35868"
	preset_id: string, // "s35868"
};

export type Station = {
	element: string, // "station",
	guide_id: string, // "s129499",
	preset_id: string, // "s129499",
	name: string, // "NPR's All Songs Considered",
	call_sign: string, // "NPR's All Songs 24/7 Music Channel",
	slogan: string, // "",
	frequency: string, // "",
	band: string, // "Stream",
	url: string, // "http://www.npr.org/music/allsongs247/",
	report_url: string, // "http://tunein.com/contact/resolve/?stationId=129499",
	detail_url: string, // "http://tun.in/seQML",
	is_preset: boolean, // false,
	is_available: boolean, // true,
	is_music: boolean, // true,
	has_song: boolean, // false,
	has_schedule: boolean, // false,
	has_topics: boolean, // false,
	twitter_id: string, // "",
	logo: string, // "http://cdn-radiotime-logos.tunein.com/s129499q.png",
	location: string, // "US",
	current_song: null,
	current_artist: null,
	current_artist_id: null,
	current_album: null,
	current_artist_art: null,
	current_album_art: null,
	description: string, // "Eclectic mix of music with a passion for indie rock spiced with 20s jazz, 60s rock folk, electronica and more",
	email: string, // "",
	phone: string, // "",
	mailing_address: string, // "",
	language: string, // "English",
	genre_id: string, // "g2748",
	genre_name: string, // "Indie Music",
	region_id: null,
	country_region_id: 100436,
	latlon: null,
	tz: string, // "Eastern",
	tz_offset: string, // "-240",
	publish_song: null,
	publish_song_url: null,
	publish_song_rejection_reason: null,
	now_playing_url: null,
	external_key: null,
	ad_eligible: boolean, // false,
	preroll_ad_eligible: boolean, // false,
	companion_ad_eligible: boolean, // false,
	video_preroll_ad_eligible: boolean, // false,
	fb_share: boolean, // true,
	twitter_share: boolean, // true,
	song_share: boolean, // true,
	donation_eligible: null,
	donation_url: null,
	donation_text: null,
	donation_icon: null,
	song_buy_eligible: null,
	tunein_url: string, // "http://tunein.com/station/?stationId=129499",
	is_family_content: boolean, // false,
	is_mature_content: boolean, // false,
	is_event: boolean, // false,
	content_classification: "music",
	echoed_count: null,
	favorited_count: null,
	is_favorited: null,
	is_favoritable: null,
	has_profile: "true",
	can_cast: boolean, // true,
	nielsen_eligible: boolean, // false,
	nielsen_provider: null,
	nielsen_asset_id: null,
	nowplaying_channel: null,
	why_ads_text: null,
	use_native_player: boolean, // false,
	live_seek_stream: boolean, // false
};
